container:
  containerimage: "OVERWRITE.acr.io/alwayson/healthservice:1234" # Container Image Name
  pullPolicy: "IfNotPresent" # Container Image Pull Policy. Using IfNotPresent to enable pod starts even if ACR cannot be reached and image was pulled on the node previously

workload:
  domainname: "OVERWRITE-cluster.eastus2.cloudapp.azure.com" # External Domain Name of the AKS cluster (used for Ingress)
  tlsSecret: workload-ingress-secret # k8s secret name for the tls cert - make sure that the name is the same when shared
  port: 8080 # Port of the container workload
  replicas: 3 # number of replicas
  service:
    port: 80 # Service Port (not used for Ingress)
    type: "ClusterIP" # Service Type (default ClusterIP)

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "cert-manager-alwayson" # this will trigger cert-manager to request a certificate

# Note! When disabling Network Policy for this helm chart,
# make sure to disable Network Policy for the CatalogService as well
# as it contains a default-deny policy.
networkPolicy:
  enabled: true # Enable Network Policy

azure:
  frontdoorid: "" # Azure Front Door Header ID
  region: "East US 2"
