# Network Policy to allow ingress traffic from * to the workload.
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-allow-external
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  ingress:
  - from: []
    ports:
    - port: {{ .Values.workload.port | default 8080 }}