# Default Network Policy applied to the workload. 
# Denies ingress and egress that is not explicitly allowed.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-deny-all
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# Network Policy to allow ingress traffic from * on Port 80 to the cert-manager HTTP issuer.
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-allow-ingress-for-cert-manager-http
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: true
  ingress:
  - from: []
    ports:
    - port: 8089 # default port for cm-acme-http-solve
---
# Network Policy to allow ingress traffic from * to the workload.
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-allow-ingress-from-external
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  ingress:
  - from: []
    ports:
    - port: {{ .Values.workload.port | default 8080 }}
---
# Network policy to allow egress / outbound traffic from the workload.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-allow-all-egress
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  egress:
  - {}
  policyTypes:
  - Egress