{{- if .Values.networkPolicy.enabled }}
# Network policy to allow egress / outbound traffic from the workload.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-allow-egress-traffic
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.egressRange | default "0.0.0.0/0" }} 
  policyTypes:
  - Egress
{{- end }}